Battleship Game C#/WebApp/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Battleship Game C#/WebApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

// namespace WebApp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Battleship Game C#/WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
    
    public RedirectToPageResult OnPostStandardGame()
    {
        return RedirectToPage("Game/StandardGame");
    }
        
    public RedirectToPageResult OnPostCustomGame()
    {
        return RedirectToPage("Game/CustomGame", "NewCustomGame");
    }

}

Battleship Game C#/WebApp/Pages/About.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Battleship Game C#/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container px-4">
    <div class="col text-center p-5">
        <h1>Welcome to Battleship</h1>
    </div>
    <div class="p-4 row gx-5">
        <div class="col text-end align-bottom">
            <form method="post" asp-page-handler="StandardGame">
                <button type="submit" class="btn-lg btn-dark">Standard Game</button>
            </form>
        </div>
        <div class="col">
            <form method="post" asp-page-handler="CustomGame">
                <button type="submit" class="btn-lg btn-dark">Custom Game</button>
            </form>
        </div>
    </div>
</div>