Battleship Game C#/WebApp/Pages/Game/BattleShip.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using BattleShipBrain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using WebApp.Pages.Game;
using JsonSerializer = System.Text.Json.JsonSerializer;
using Player = Domain.Player;

namespace WebApp.Pages
{
    public class BattleShip : PageModel
    {
        public static string Info { get; set; } = "";

        public static BSBrain Brain { get; set; } = new BSBrain();

        public static int PlayerNumber { get; set; } = 0;
        public static int ShipIndex { get; set; } = 0;
        public static List<Ship> Ships { get; set; } = new List<Ship>();
        public static Ship TempShip { get; set; } = new Ship("default", 0, 0);
        public static List<(int, int)> ShipCords { get; set; } = new List<(int, int)>();

        public static bool Bombing = false;
        
        public static bool FirsTime = true;

        public static int ContainterSize = 5;
        
        public IActionResult OnGet(int x, int y, bool bombing)
        {
            
            if (Bombing == false)
            {
                Placing(x, y);
                return Page();
            }

            if (FirsTime)
            {
                Info = "Game Start";
                FirsTime = false;
                return Page();
            }
            
            if (!Brain.PlaceBombSquare(x, y))
            {
                Info = "Already placed a bomb there!";
                return Page();
            }

            Info =
                $"Player {Brain.CurrentPlayerInt + 1} placed a bomb at ({x + 1}, {y + 1}) ";

            var ship = Brain.FindSelectedShip(true, x, y);

            if (ship != null)
            {
                if (ship.IsShipSunk(Brain.EnemyPlayer.Board))
                {
                    Info += $"which sunks enemy's {ship.Name}!";
                }
                else
                {
                    Info += "which was a hit!";
                }
            }
            else
            {
                Info += "which was a miss!";
            }
            
            Brain.UpdatePlayer();
            
            if (Brain.CheckWinCondition())
            {
                return RedirectToPage("Victory");
            }
            
            return Page();
        }

        public void Placing(int cordX, int cordY)
        {
            while (cordX + TempShip.X > Brain.GameConfig.BoardSizeX)
            {
                cordX -= 1;

                if (cordX <= 0)
                {
                    break;
                }
            }

            while (cordY + TempShip.Y > Brain.GameConfig.BoardSizeY)
            {
                cordY -= 1;

                if (cordY <= 0)
                {
                    break;
                }
            }

            ShipCords = new List<(int, int)>();

            for (int x = cordX; x < cordX + TempShip.X; x++)
            {
                for (int y = cordY; y < cordY + TempShip.Y; y++)
                {
                    ShipCords.Add((x, y));
                }
            }
        }

        public void OnGetRandomStandard(string gameName)
        {
            Info = "";
            FirsTime = false;
            Brain = new BSBrain();
            Brain.GameConfig.Name = gameName;
            Brain.InitializeBoards();
            Brain.GenerateRandomBoards();
            Bombing = true;
        }
        
        public void OnGetCustomStandard(string gameName)
        {
            Info = "Place ships for player " + (Brain.CurrentPlayerInt + 1);

            Brain = new BSBrain();
            Brain.GameConfig.Name = gameName;
            FirsTime = true;
            ShipCords = new List<(int, int)>();
            Brain.InitializeBoards();
            PlayerNumber = 0;
            ShipIndex = 0;
            Ships = Brain.GameConfig.Ships;
            TempShip = new Ship(Ships[ShipIndex].Name, Ships[ShipIndex].X, Ships[ShipIndex].Y);
            Bombing = false;
        }
        
        public void OnGetCustomGame()
        {
            Info = "Place ships for player " + (Brain.CurrentPlayerInt + 1);
            var brain = new BSBrain();

            GameConfig gameConfig = new GameConfig();
            TempData.TryGetValue("GameConfig", out var jsonGameConfig);

            if (jsonGameConfig != null)
            {
                gameConfig = JsonConvert.DeserializeObject<GameConfig>((string) jsonGameConfig);
            }

            TempData.TryGetValue("GameConfig", out var jsonShips);
            

            if (gameConfig != null)
            {
                gameConfig.Ships.RemoveRange(0, 5);
                
                ShipCords = new List<(int, int)>();
                FirsTime = true;
                Brain = brain;
                PlayerNumber = 0;
                ShipIndex = 0;
                Ships = gameConfig.Ships;
                TempShip = new Ship(Ships[ShipIndex].Name, Ships[ShipIndex].X, Ships[ShipIndex].Y);
                Bombing = false;
                
                Brain.GameConfig = gameConfig;
                Brain.InitializeBoards();
                
            }
            else
            {
                RedirectToPage("/Error");
            }
        }

       

        public void OnPostRotateShip()
        {
            Ship ship = Ships[ShipIndex];

            TempShip.Rotate();
            OnGet(ShipCords[0].Item1, ShipCords[0].Item2, false);
        }

        public IActionResult OnPostPlaceShip()
        {
            Info = "Place ships for player " + (Brain.CurrentPlayerInt + 1);
            
            if (!Brain.PlaceShip(TempShip, ShipCords[0].Item1, ShipCords[0].Item2))
            {
                Info = "Can't place ship there";
                return Page();
            }
            

            ShipIndex += 1;

            if (ShipIndex + 1 > Ships.Count)
            {
                ShipIndex = 0;
                PlayerNumber += 1;
                Brain.UpdatePlayer();

                if (PlayerNumber > 1)
                {
                    ViewData["brain"] = Brain;
                    Bombing = true;
                }
            }

            TempShip = new Ship(Ships[ShipIndex].Name, Ships[ShipIndex].X, Ships[ShipIndex].Y);;

            OnGet(ShipCords[0].Item1, ShipCords[0].Item2, false);
            
            return Page();
        }


        public void OnPostRedoMove()
        {
            if (Brain.RedoMove())
            {
                Info = "Redid the move!";
            }
        }

        public void OnPostUndoMove()
        {
            if (Brain.UndoMove())
            {
                Info = "Undid the previous move!";
            }
        }

        public void OnPostSaveGameDb()
        {
            Brain.SaveGameToDb(true);
        }

        public void OnPostSaveGameJson()
        {
            Info = "Saved a game to " + System.IO.Path.DirectorySeparatorChar + "Saves";
            
            var conf = Brain.GetBrainJson();

            var jsonOptions = new JsonSerializerOptions()
            {
                WriteIndented = true
            };

            var fileNameStandardConfig = "" + System.IO.Path.DirectorySeparatorChar + "Saves" +
                                         System.IO.Path.DirectorySeparatorChar + $"{Brain.GameConfig.Name}.json";

            var confJsonStr = JsonSerializer.Serialize(conf, jsonOptions);

            if (!System.IO.File.Exists(fileNameStandardConfig))
            {
                System.IO.File.WriteAllText(fileNameStandardConfig, conf);
            }
        }

        public void OnGetLoadGameDb(int id)
        {
            Info = "Saved a game to the database with the name " + Brain.GameConfig.Name;
            Info = "";
            Brain.LoadGameFromDb(id);
            Bombing = true;
        }

        public void OnGetLoadGameJson(int id)
        {
            Info = "";
            string[] saveFiles =
                Directory.GetFiles("" + System.IO.Path.DirectorySeparatorChar + "Saves", "*.json");
            Brain.RestoreBrainFromJson(System.IO.File.ReadAllText(saveFiles[id]));
            Bombing = true;
        }


        public RedirectToPageResult OnPostExitGame()
        {
            return RedirectToPage("/Index");
        }
    }
}

Battleship Game C#/WebApp/Pages/Game/CustomGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BattleShipBrain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace WebApp.Pages.Game
{
    
    public class CustomGame : PageModel
    {
        
        [BindProperty]
        public Domain.GameConfig GameConfigModel { get; set; } = default!;
        public static List<Ship> GameShips { get; set; } = new List<Ship>();

        [TempData] 
        public string GameConfig { get; set; } = null!;

        public static bool ShipNameError { get; set; } = false;
        public static bool ShipXError { get; set; } = false;
        public static bool ShipYError { get; set; } = false;

        public static string ShipNameValue { get; set; } = "";
        public static string ShipXValue { get; set; } = "";
        public static string ShipYValue { get; set; } = "";
        
        public IActionResult OnGet(int id)
        {
            GameShips.RemoveAt(id);

            return Page();
        }
        
        public void OnGetNewCustomGame()
        {
            GameShips = new List<Ship>();
        }
        
        public IActionResult OnPostAddShip()
        {
            ShipNameValue = Request.Form["shipName"];
            ShipXValue = Request.Form["shipX"];
            ShipYValue = Request.Form["shipY"];
            
            
            if (Request.Form["shipName"] == "")
            {
                ShipNameError = true;
            }
            else
            {
                ShipNameError = false;
            }
            
            if (int.TryParse(Request.Form["shipX"], out int x))
            {
                ShipXError = false;
                
                if (int.TryParse(Request.Form["shipY"], out int y))
                {
                    ShipYError = false;

                    if (!ShipNameError)
                    {
                        GameShips.Add(new Ship(ShipNameValue, x, y));   
                        
                        ShipNameValue = "";
                        ShipXValue = "";
                        ShipYValue = "";
                    }
                }
                
            }
            else
            {
                ShipXError = true;
                if (!int.TryParse(Request.Form["shipY"], out var y))
                {
                    ShipYError = true;
                }
            }

            return Page();
        }
        public IActionResult OnPostCreateGame()
        {
            if (!ModelState.IsValid || GameShips.Count == 0)
            {
                return Page();
            }
            
            if (int.TryParse(Request.Form["gameRule"], out var gameRule))
            {
                var gameConfig = new GameConfig()
                {
                    Name = GameConfigModel.GameName,
                    BoardSizeX = GameConfigModel.BoardSizeX,
                    BoardSizeY = GameConfigModel.BoardSizeY,
                    EShipTouchRule = (EShipTouchRule) gameRule,
                    Ships = GameShips
                };
                
                GameConfig = JsonConvert.SerializeObject(gameConfig);
                return RedirectToPage("BattleShip", "CustomGame");
            }

            return Page();
        }

    }
    
    
    
}

Battleship Game C#/WebApp/Pages/Game/LoadGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DAL;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Pages.Game
{
    
    
    public class LoadGame : PageModel
    {

        public static List<string> GameNames = new List<string>();

        public static bool LoadFromDb = false;

        public void OnGet()
        {
            OnPostListGamesJson();
        }

        public void OnPostListGamesDb()
        {
            GameNames.Clear();
            LoadFromDb = true;
            using var db = new AppDbContext();
            
            var gameConfigsFromDb = db.GameConfigs;
            
            foreach (var gameConfig in gameConfigsFromDb)
            {
                GameNames.Add(gameConfig.GameName);
            }
        }
        
        public void OnPostListGamesJson()
        {
            GameNames.Clear();
            LoadFromDb = false;
            string[] saveFiles =
                Directory.GetFiles("" + System.IO.Path.DirectorySeparatorChar + "Saves", "*.json");

            for (int i = 0; i < saveFiles.Length; i++)
            {
                GameNames.Add(saveFiles[i].Split(System.IO.Path.DirectorySeparatorChar).Last().Split(".")
                    .First());    
            }
            
        }
        
    }
}

Battleship Game C#/WebApp/Pages/Game/StandardGame.cshtml.cs
using System;
using System.Reflection.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Game
{
    public class StandardGame : PageModel
    {
        
        public void OnGet()
        {
            
        }
        
        public RedirectToPageResult OnPostRandomGame()
        {
            return RedirectToPage("BattleShip", "RandomStandard", new {gameName = Request.Form["Name"]});
        }
        
        public RedirectToPageResult OnPostCustomGame()
        {
            return RedirectToPage("BattleShip", "CustomStandard", new {gameName = Request.Form["Name"]});
        }
        
    }
}

Battleship Game C#/WebApp/Pages/Game/Victory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Game
{
    public class Victory : PageModel
    {
        public void OnGet()
        {
            
        }

        public RedirectToPageResult OnPost()
        {
            
            return RedirectToPage("/Index");
            
        }
        
    }
}

Battleship Game C#/WebApp/Pages/Game/BattleShip.cshtml
@page
@using System.Drawing
@model WebApp.Pages.BattleShip

@{
    ViewData["Title"] = "Battle Ship";
}

<div class="container">
<div style="border-bottom: 2px solid gray;  height: 50px; width: @BattleShip.Brain.SelectedIndexY * 2" class="row " align="center">
    <h2>@BattleShip.Info</h2>
</div>

<div class="row">
<div class="col-md-6 pt-4" align="right">
    <div class="col">
        <table style="border: 1px solid black">
            @if (BattleShip.Bombing)
            {
                @for (int x = 0; x < BattleShip.Brain.GameConfig.BoardSizeX; x++)
                {
                    <tr style="height: 50px;border: 1px solid black;">
                        @for (int y = 0; y < BattleShip.Brain.GameConfig.BoardSizeY; y++)
                        {
                            var sunken = false;
                            var ship = BattleShip.Brain.FindSelectedShip(true, x, y);

                            if (ship != null)
                            {
                                sunken = ship.IsShipSunk(BattleShip.Brain.EnemyPlayer.Board);
                            }

                            var color = UIElements.ColorSquare(
                                BattleShip.Brain.GetBoard(1 - BattleShip.Brain.CurrentPlayerInt)[(x, y)],
                                true, sunken);

                            <td onclick="window.location.href = '/Game/BattleShip?x=@x&y=@y&bombing=true' "style="width: 50px; cursor: pointer; border: 1px solid black; background: @color"></td>
                        }
                    </tr>
                }
            }
            else
            {
                @for (int x = 0; x < BattleShip.Brain.GameConfig.BoardSizeX; x++)
                {
                    <tr style="height: 50px;border: 1px solid black;">
                        @for (int y = 0; y < BattleShip.Brain.GameConfig.BoardSizeY; y++)
                        {
                            string color;

                            if (BattleShip.ShipCords.Contains((x, y)))
                            {
                                if (!BattleShip.Brain.GetCurrentPlayer().AvailableCoordinates.Contains((x,y)))
                                {
                                    color = ColorTranslator.ToHtml(Color.Red);
                                }
                                else
                                {
                                    color = ColorTranslator.ToHtml(Color.Green);
                                }
                            }
                            else if (!BattleShip.Brain.GetCurrentPlayer().AvailableCoordinates.Contains((x,y)))
                            {
                                if (BattleShip.Brain.GetBoard(BattleShip.PlayerNumber)[(x, y)].IsShip)
                                {
                                    color = ColorTranslator.ToHtml(Color.Black);
                                }
                                else
                                {
                                    color = ColorTranslator.ToHtml(Color.Gray);
                                }
                            }
                            else
                            {
                                color = ColorTranslator.ToHtml(Color.White);
                            }

                            <td onclick="window.location.href = '/Game/BattleShip?x=@x&y=@y&bombing=false' "style="width: 50px; cursor: pointer; border: 1px solid black; background: @color"></td>
                        }
                    </tr>
                }
            }
        </table>

    </div>
</div>
<div class="col-md-3 pt-4">
    <div class="col">
        @if (BattleShip.Bombing)
        {
            <table class="" style="border: 1px solid black">
                @for (int x = 0; x < BattleShip.Brain.GameConfig.BoardSizeX; x++)
                {
                    <tr style="height: 25px;border: 1px solid black;">
                        @for (int y = 0; y < BattleShip.Brain.GameConfig.BoardSizeY; y++)
                        {
                            var sunken = false;
                            var ship = BattleShip.Brain.FindSelectedShip(true, x, y);

                            if (ship != null)
                            {
                                sunken = ship.IsShipSunk(BattleShip.Brain.CurPlayer.Board);
                            }

                            var color = UIElements.ColorSquare(
                                BattleShip.Brain.GetBoard(BattleShip.Brain.CurrentPlayerInt)[(x, y)],
                                false, sunken);

                            <td style="width: 25px; cursor: pointer; border: 1px solid black; background: @color"></td>
                        }
                    </tr>
                }
            </table>
        }
        @if (BattleShip.Brain.GameConfig.BoardSizeY < 5)
        {
            BattleShip.ContainterSize = 5;
        }
        else
        {
            BattleShip.ContainterSize = BattleShip.Brain.GameConfig.BoardSizeY;
        }
        <div class="col-md-3 pt-3" style="width: @(25 * BattleShip.ContainterSize)px">
            <div class="d-grid gap-2">
                @if (BattleShip.Bombing)
                {
                    @if (BattleShip.Brain._bombingHistory.Count == 0)
                    {
                        <button type="button" class="btn btn-primary btn-dark" disabled>Undo Move</button>
                    }
                    else
                    {
                        <form asp-page-handler="UndoMove" method="post" class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary btn-dark">Undo Move</button>
                        </form>
                    }

                    @if (BattleShip.Brain._redoHistory.Count == 0)
                    {
                        <button type="button" class="btn btn-primary btn-dark" disabled>Redo Move</button>
                    }
                    else
                    {
                        <form asp-page-handler="RedoMove" method="post" class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary btn-dark">Redo Move</button>
                        </form>
                    }

                    <form asp-page-handler="SaveGameDb" method="post" class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-success">Save Game Db</button>
                    </form>

                    <form asp-page-handler="SaveGameJson" method="post" class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary btn-success">Save Game Json</button>
                    </form>
                }
                else
                {
                    if (BattleShip.ShipCords.Count == 0)
                    {
                        <button type="submit" class="btn btn-primary btn-primary" disabled>Rotate Ship</button>
                    }
                    else
                    {
                        <form asp-page-handler="RotateShip" method="post" class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary btn-primary">Rotate Ship</button>
                        </form>
                    }

                    if (BattleShip.ShipCords.Count == 0)
                    {
                        <button type="submit" class="btn btn-primary btn-success" disabled>Place Ship</button>
                    }
                    else
                    {
                        <form asp-page-handler="PlaceShip" method="post" class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary btn-success">Place Ship</button>
                        </form>
                    }
                }
                <form asp-page-handler="ExitGame" method="post" class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary btn-danger">Exit Game</button>
                </form>

            </div>
        </div>
    </div>
</div>
<div class="col-md-3 pt-5">
    <div class="col" style="width: @(25 * BattleShip.ContainterSize)px">
        <div class="d-grid gap-2">
            <table>
                <thead>
                <tr>
                    <th>Current Player:</th>
                    <th>@(BattleShip.Brain.CurrentPlayerInt + 1)</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Number of ships</td>
                    <td>@BattleShip.Brain.GameConfig.Ships.Count</td>
                </tr>
                <tr>
                    <td>Ship placement rule:</td>
                    <td>@BattleShip.Brain.GameConfig.EShipTouchRule</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Board heigth:</td>
                    <td>@BattleShip.Brain.GameConfig.BoardSizeX</td>
                </tr>
                <tr>
                    <td>Board length:</td>
                    <td>@BattleShip.Brain.GameConfig.BoardSizeY</td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
</div>

</div>
</div>

Battleship Game C#/WebApp/Pages/Game/CustomGame.cshtml
@page
@model WebApp.Pages.Game.CustomGame

@{
    ViewData["Title"] = "Custom Game";
}

<div class="container">
    <div class="row">
        <div class="col-md-6 pt-4">
            <h2>Game Settings:</h2>
            <form class="p-3" asp-page-handler="CreateGame">
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="gameName" class="form-label">Game Name</label>
                        <input asp-for="GameConfigModel.GameName" type="text" id="gameName" class="form-control" required>
                        <span class="form-text text-danger" asp-validation-for="GameConfigModel.GameName"></span>
                        <div class="form-text">Displayed on the save file</div>
                    </div>
                    <div class="col-md-6 mb-3 align-middle">
                        <label for="selectGameRule" class="form-label">Ship Placement Rule</label>
                        <select class="form-select" name="gameRule" id="selectGameRule" aria-label="Default select example">
                            <option selected value="0">No Touch</option>
                            <option value="1">Corner Touch</option>
                            <option value="2">Side Touch</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <label class="form-label pb-1">Board diameters</label>
                    <div class="col-md-6 mb-3 form-check">
                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text">Heigth</span>
                            @* <input type="text" class="form-control" name="boardX" aria-label="Sizing example input"> *@
                            <input asp-for="GameConfigModel.BoardSizeX" type="text" class="form-control" required>
                            <span class="form-text text-danger" asp-validation-for="GameConfigModel.BoardSizeX"></span>
                        </div>
                    </div>
                    <div class="col-md-6 mb-3 form-check">
                        <div class="input-group input-group-sm mb-3">
                            <span class="input-group-text">Length</span>
                            <input asp-for="GameConfigModel.BoardSizeY" type="text" class="form-control" required>
                            <span class="form-text text-danger" asp-validation-for="GameConfigModel.BoardSizeY"></span>
                        </div>
                    </div>
                </div>
                <div class="col" align="right">
                    <button type="submit" class="btn btn-primary">Create Game</button>
                </div>
                <div class="col pt-2" align="right">
                    <a type="button" class="btn btn-danger " asp-page="/Index">Back</a>
                </div>
            </form>

        </div>

        <div class="col-md-6 pt-4">
            
            <h2>Ships:</h2>

            <form class="rounded border p-3" asp-page-handler="AddShip">
                <div class="col-md-6 mb-1">
                    <label for="ShipsName" class="form-label">Ship Name</label>
                    <input name="shipName" value="@CustomGame.ShipNameValue" type="text" class="form-control" id="ShipsName" aria-describedby="emailHelp">
                </div>
                @if (CustomGame.ShipNameError)
                {
                    <span class="form-text text-danger">Ship Name cannot be empty</span>
                }
                <div class="row">
                    <label class="form-label pb-1">Ship Size</label>
                    <div class="col-md-6 mb-1 form-check">
                        <div class="row">
                            <div class="input-group input-group-sm">
                                <span for="shipsHeight" class="input-group-text">Height</span>
                                <input name="shipX" type="text" value="@CustomGame.ShipXValue" class="form-control" id="shipsHeight">
                            </div>
                        </div>

                        @if (CustomGame.ShipXError)
                        {
                            <span class="form-text text-danger">Must be between 1 and 20</span>
                        }

                    </div>
                    <div class="col-md-6 mb-1 form-check">
                        <div class="input-group input-group-sm mb-1">
                            <span for="shipsLength" class="input-group-text">Length</span>
                            <input name="shipY" type="text" id="shipsLength" value="@CustomGame.ShipYValue" class="form-control" aria-describedby="Ships length">
                        </div>

                        @if (CustomGame.ShipYError)
                        {
                            <span class="form-text text-danger">Must be between 1 and 20</span>
                        }
                    </div>
                </div>

                <div class="col" align="right">
                    <button type="submit" class="btn btn-success">Add Ship</button>
                </div>

            </form>

            @for (int i = 0; i < CustomGame.GameShips.Count; i++)
            {
                var ship = CustomGame.GameShips[i];

                <li class="list-group-item d-flex justify-content-between align-items-center">
                    | @ship.Name | Height: @ship.X | Lenght: @ship.Y |
                    <button onclick="window.location.href = '/Game/CustomGame?id=@i'" class="btn btn-danger">X</button>
                </li>
            }
            <ul class="list-group">

            </ul>


        </div>
    </div>
</div>

Battleship Game C#/WebApp/Pages/Game/LoadGame.cshtml
@page
@model WebApp.Pages.Game.LoadGame

@{
    ViewData["Title"] = "Load Game";
}

<div class="row">
    <div class="col">
        @if (LoadGame.LoadFromDb)
        {
            <h2>Database games</h2>
        }
        else
        {
            <h2>Local games</h2>
        }
    </div>

    <div class="col" align="right">
        @if (LoadGame.LoadFromDb)
        {
            <form method="post" asp-page-handler="ListGamesJson">
                <button type="submit" class="btn btn-dark">List Local Files</button>
            </form>
        }
        else
        {
            <form method="post" asp-page-handler="ListGamesDb">
                <button type="submit" class="btn btn-dark">List Database Files</button>
            </form>
        }
    </div>
</div>
<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Game Name</th>
        <th scope="col">-</th>
    </tr>
    </thead>
    <tbody>

    @for (int i = 0; i < LoadGame.GameNames.Count; i++)
    {
        <tr>
            <th scope="row">@(i + 1)</th>
            <td>@LoadGame.GameNames[i]</td>
            <td align="right">
                @if (LoadGame.LoadFromDb)
                {
                    <button onclick="window.location.href = '/Game/BattleShip?handler=LoadGameDb&id=@(i + 1)'" class="btn btn-success">Load</button>
                }
                else
                {
                    <button onclick="window.location.href = '/Game/BattleShip?handler=LoadGameJson&id=@(i)'" class="btn btn-success">Load</button>
                }
            </td>
        </tr>
    }

    </tbody>
</table>

Battleship Game C#/WebApp/Pages/Game/Victory.cshtml
@page
@model WebApp.Pages.Game.Victory

<div class="container px-4">
    <div class="row text-center p-5">
        <h1>!!!   Player @(1 - BattleShip.Brain.CurrentPlayerInt + 1) won   !!!</h1>
    </div>
    <div class="p-4 row gx-5">
        <div class="col text-center align-bottom">
            <form method="post" >
            <button type="submit" class="btn-lg btn-dark">Continue</button>
            </form>
        </div>
    </div>
</div>